name: Deploy to Server with Caddy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install and Build
      run: |
        npm ci
        npm run build

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.DEPLOY_SERVER }}
        username: your_server_username
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          rm -rf /path_to_your_deploy_folder/*
          mkdir -p /path_to_your_deploy_folder
    
    - name: Copy dist folder to server
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.DEPLOY_SERVER }}
        username: your_server_username
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./dist/*"
        target: "/path_to_your_deploy_folder"
