name: Playwright Tests

on: [push, pull_request]

concurrency:
  group: playwright-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Navigate to app directory
      run: cd app

    - name: Install dependencies
      working-directory: app
      run: npm ci

    - name: Build and start server
      run: |
        npm run build
        npm run start & # This starts the server in the background
        sleep 5 # Allow the server some time to start

    - name: Run Playwright tests
      working-directory: app
      run: npm run test:e2e

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
